-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "public"."Visibility" AS ENUM('PUBLIC', 'PRIVATE', 'DELETED');--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "InstagramFeed" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""InstagramFeed_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"posts" text[] NOT NULL,
	"page" varchar NOT NULL
);

*/